name: Instalar Dependencias

on:
  push:
    branches:
      - main

jobs:
  build:
   -on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Instalar Dependencias de Node.js
      run: npm install express node-fetch
